ekf_filter_node:
  ros__parameters:
    # Core EKF settings
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    # Frames (fill these to match your robot)
    map_frame: map
    odom_frame: odom       # e.g., "odom"
    base_link_frame: base_footprint    # e.g., "base_link"
    world_frame: odom       # typical: "odom" for localization w.r.t odom

    # ===== Wheel Odometry input =====
    odom0: /odom
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    # Which state variables to fuse from /odom:
    # [x, y, z,
    #  roll, pitch, yaw,
    #  vx, vy, vz,
    #  v_roll, v_pitch, v_yaw,
    #  ax, ay, az]
    odom0_config:
      - true   # x
      - true   # y
      - false  # z
      - false  # roll
      - false  # pitch
      - true   # yaw
      - true   # vx
      - false  # vy
      - false  # vz
      - false  # v_roll
      - false  # v_pitch
      - true   # v_yaw
      - false  # ax
      - false  # ay
      - false  # az

    # ===== IMU input =====
    imu0: /imu
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 50
    imu0_remove_gravitational_acceleration: true

    # Fuse IMU orientation (yaw) + angular velocity (yaw rate). Linear accel can be noisy; start disabled.
    imu0_config:
      - false  # x
      - false  # y
      - false  # z
      - false  # roll
      - false  # pitch
      - true   # yaw
      - false  # vx
      - false  # vy
      - false  # vz
      - false  # v_roll
      - false  # v_pitch
      - true   # v_yaw
      - false  # ax
      - false  # ay
      - false  # az

    # Process noise & initial estimates (reasonable defaults; you can tune later)
    process_noise_covariance: [  # 15x15 flattened row-major
      0.05, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,
      0.0, 0.05, 0.0, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 1e3, 0.0, 0.0, 0.0,    0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 1e3, 0.0, 0.0,    0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 1e3, 0.0,    0.0, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.05,   0.0, 0.0, 0.0, 0.0, 0.0, 0.02,  0.0, 0.0, 0.0,

      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      0.2, 0.0, 0.0, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      0.0, 1e2, 0.0, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      0.0, 0.0, 1e2, 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,

      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      0.0, 0.0, 0.0, 1e2, 0.0, 0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      0.0, 0.0, 0.0, 0.0, 1e2, 0.0,   0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      0.0, 0.0, 0.0, 0.0, 0.0, 0.1,   0.0, 0.0, 0.0,

      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,     1e2, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,     0.0, 1e2, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      0.0, 0.0, 0.0, 0.0, 0.0, 0.0,     0.0, 0.0, 1e2
    ]
